openapi: "3.0.3"
info:
  title: "I Love Animals API"
  description: "I Love Animals API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
tags:
  - name: Auth
  - name: User Profile
  - name: Advertisement
  - name: Veterinary Clinic
  - name: Search
  - name: Advertisement Comments
  - name: Charity Score
paths:
  /register:
    post:
      tags:
        - Auth
      summary: "Register"
      requestBody:
        description: Register user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterModel"
      responses:
        200:
          description: "Successfully created!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /login:
    post:
      tags:
        - Auth
      summary: "Login"
      requestBody:
        description: Login user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginModel"
      responses:
        200:
          description: "Successfully logged in"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"

  /user/{userId}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - User Profile
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User UUID
      responses:
        200:
          description: User Profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileResponse"
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - User Profile
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User UUID
      requestBody:
        description: Update Request Object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequest"
      responses:
        200:
          description: "Successfully updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /advertisement-list:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement
      summary: "Advertisement List"
      responses:
        200:
          description: "Advertisement List"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertisementResponse"

  /advertisement-list/{category}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement
      summary: "Advertisement List by Category"
      parameters:
        - in: path
          name: category
          required: true
          schema:
            type: integer
          description: Category
      responses:
        200:
          description: "Advertisement List"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertisementResponse"

  /add-advertisement:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement
      summary: "Add new advertisement"
      requestBody:
        description: Add new advertisement
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvertisementRequest"
      responses:
        200:
          description: "Successfully added new advertisement!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /advertisement/{id}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The advertisement UUID
      responses:
        200:
          description: An advertisement by ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertisementResponse"

    put:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The advertisement UUID
      requestBody:
        description: Add new advertisement
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAdvertisementRequest"

      responses:
        200:
          description: "Successfully updated advertisement!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The advertisement UUID
      responses:
        200:
          description: "Successfully deleted advertisement!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /user-advertisement/{userId}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The user UUID
      responses:
        200:
          description: User advertisement list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertisementResponse"

  /search:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Search
      parameters:
        - in: query
          name: key
          required: true
          schema:
            type: string
          description: Keyword
      summary: "Search Advertisement"
      responses:
        200:
          description: Searched Advertisement List
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertisementResponse"

  /advertisement/{id}/comments:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement Comments
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The advertisement UUID
      responses:
        200:
          description: Advertisement comment list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertisementCommentResponse"

  /advertisement/{id}/comment:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement Comments
      summary: "Add new comment for an advertisement"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The advertisement UUID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvertisementCommentRequest"
      responses:
        200:
          description: "Successfully added new advertisement comment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /comment/{commentId}:
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement Comments
      parameters:
        - in: path
          name: commentId
          required: true
          schema:
            type: string
          description: Comment ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvertisementCommentRequest"
      responses:
        200:
          description: "Successfully updated advertisement comment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - Advertisement Comments
      parameters:
        - in: path
          name: commentId
          required: true
          schema:
            type: string
          description: Comment ID
      responses:
        200:
          description: "Successfully deleted advertisement comment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /charity-score:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Charity Score
      responses:
        200:
          description: Charity Score Table
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CharityScore"
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - Charity Score
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateScoreRequest"
      responses:
        200:
          description: "Successfully updated charity score"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /clinics:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - Veterinary Clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VeterinaryClinicRequest"
      responses:
        200:
          description: "Successfully added the veterinary clinic"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
  /clinics/{postalCode}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Veterinary Clinic
      parameters:
        - in: path
          name: postalCode
          required: true
          schema:
            type: string
          description: Comment ID
      responses:
        200:
          description: "Nearby Veterinary clinics"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VeterinaryClinic"
components:
  schemas:
    RegisterModel:
      type: object
      properties:
        fullName:
          type: string
        email:
          type: string
        password:
          type: string
        phoneNumber:
          type: string
        profileImageUrl:
          type: string
    MessageResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
    LoginModel:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
        token:
          type: string
    AdvertisementResponse:
      type: object
      properties:
        id:
          type: string
        creatorId:
          type: string
        title:
          type: string
        description:
          type: string
        category:
          type: integer
        images:
          type: array
          items:
            type: string
        location:
          $ref: "#/components/schemas/Location"
        address:
          type: string
        isCompleted:
          type: boolean
        createdAt:
          type: string
    Location:
      type: object
      properties:
        longitude:
          type: string
        latitude:
          type: string

    AdvertisementRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        category:
          type: integer
        images:
          type: array
          items:
            type: string
        longitude:
          type: string
        latitude:
          type: string
        address:
          type: string
    UpdateAdvertisementRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        category:
          type: integer
        address:
          type: string
        isCompleted:
          type: boolean
    AdvertisementCommentResponse:
      type: object
      properties:
        commentId:
          type: number
        comment:
          type: string
        advertisementId:
          type: string
        userId:
          type: string
    AdvertisementCommentRequest:
      type: object
      properties:
        comment:
          type: string
    ProfileResponse:
      type: object
      properties:
        profileId:
          type: integer
        userId:
          type: string
        fullName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        profileImageUrl:
          type: string
        charityScorePoint:
          type: integer
        bio:
          type: string
          default: null
        twitterLink:
          type: string
          default: null
        instagramLink:
          type: string
          default: null
    UpdateProfileRequest:
      type: object
      properties:
        bio:
          type: string
          default: null
        twitterLink:
          type: string
          default: null
        instagramLink:
          type: string
          default: null
    CharityScore:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: string
        userMail:
          type: string
        userFullName:
          type: string
        userImageUrl:
          type: string
        point:
          type: integer
    UpdateScoreRequest:
      type: object
      properties:
        userId:
          type: string
        point:
          type: integer

    VeterinaryClinic:
      type: object
      properties:
        id:
          type: number
        clinicName:
          type: string
        doctorName:
          type: string
        longitude:
          type: string
        latitude:
          type: string
        address:
          type: string
        postalCode:
          type: string
        openTimes:
          type: string
        closeTimes:
          type: string
        isAmbulanceAvailable:
          type: boolean
        images:
          type: array
          items:
            type: string
        phoneNumber:
          type: string
    VeterinaryClinicRequest:
      type: object
      properties:
        clinicName:
          type: string
        doctorName:
          type: string
        longitude:
          type: string
        latitude:
          type: string
        address:
          type: string
        postalCode:
          type: string
        openTimes:
          type: string
        closeTimes:
          type: string
        isAmbulanceAvailable:
          type: boolean
        images:
          type: array
          items:
            type: string
        phoneNumber:
          type: string


  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT