openapi: "3.0.3"
info:
  title: "I Love Animals API"
  description: "I Love Animals API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
tags:
  - name: Auth
  - name: Advertisement
paths:
  /register:
    post:
      tags:
        - Auth
      summary: "Register"
      requestBody:
        description: Register user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterModel"
      responses:
        200:
          description: "Successfully created!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResponse"

  /login:
    post:
      tags:
        - Auth
      summary: "Login"
      requestBody:
        description: Login user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginModel"
      responses:
        200:
          description: "Successfully logged in"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"

  /advertisement-list:
    get:
      security:
        - bearerAuth: []
      tags:
        - Advertisement
      summary: "Advertisement List"
      responses:
        200:
          description: "Advertisement List"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvertisementResponse"

  /add-advertisement:
    post:
      security:
        - bearerAuth: []
      tags:
        - Advertisement
      summary: "Add new advertisement"
      requestBody:
        description: Add new advertisement
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvertisementRequest"
      responses:
        200:
          description: "Successfully added new advertisement!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResponse"

components:
  schemas:
    RegisterModel:
      type: object
      properties:
        fullName:
          type: string
        email:
          type: string
        password:
          type: string
        phoneNumber:
          type: string
        profileImageUrl:
          type: string
    PostResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
    LoginModel:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
        token:
          type: string
    AdvertisementResponse:
      type: object
      properties:
        id:
          type: string
        creatorId:
          type: string
        title:
          type: string
        description:
          type: string
        category:
          type: integer
        images:
          type: array
          items:
            type: string
        location:
          $ref: "#/components/schemas/Location"
        isCompleted:
          type: boolean
        createdAt:
          type: string
    Location:
      type: object
      properties:
        longitude:
          type: string
        latitude:
          type: string

    AdvertisementRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        category:
          type: integer
        images:
          type: array
          items:
            type: string
        longitude:
          type: string
        latitude:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT