openapi: "3.0.3"
info:
  title: "I Love Animals API"
  description: "I Love Animals API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
tags:
  - name: Auth
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"

  /register:
    post:
      tags:
        - Auth
      summary: "Register"
      requestBody:
        description: Register user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterModel"
      responses:
        200:
          description: "Successfully created!"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"

  /login:
    post:
      tags:
        - Auth
      summary: "Login"
      requestBody:
        description: Login user object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginModel"
      responses:
        200:
          description: "Successfully logged in"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"

components:
  schemas:
    RegisterModel:
      type: object
      properties:
        fullName:
          type: string
        email:
          type: string
        password:
          type: string
        phoneNumber:
          type: string
        profileImageUrl:
          type: string
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
    LoginModel:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
        token:
          type: string